package com.jbbcch.smarttaskmanager.security.shared;

public enum Permission {
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    READ_TASK,
    ASSIGN_TASK,

    CREATE_PROJECT,
    UPDATE_PROJECT,
    READ_PROJECT,
    DELETE_PROJECT,
    ASSIGN_PROJECT,

    CREATE_ROLE,
    UPDATE_ROLE,
    READ_ROLE,
    DELETE_ROLE,
    ASSIGN_ROLE,

    CREATE_DEPARTMENT,
    UPDATE_DEPARTMENT,
    READ_DEPARTMENT,
    DELETE_DEPARTMENT,

    CREATE_USER,
    UPDATE_USER,
    READ_USER,
    DELETE_USER,
}
